name: Build PBNG Launcher EXE Portable
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx electron-builder --win portable nsis --x64 --publish never
      - uses: actions/upload-artifact@v4
        with:
          name: PBNG-Launcher-v18.2.0-with-Icon
          path: dist/*.exe
